version: '3'

services:
    back-end:
        build: ./backend
        command: gunicorn --bind 0:8000 app.wsgi:application  --reload
        volumes:
            - ./backend:/app
        ports:
            - 8000:8000
        env_file:
            - ./.env
        restart: on-failure
    nginx:
        build: ./nginx
        ports:
            - 80:80    
        depends_on:
            - back-end
        
