FROM python:3.8.0-slim as builder
RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --user -r requirements.txt


FROM python:3.8.0-slim as app

COPY --from=builder /root/.local /root/.local
COPY . /app

WORKDIR /app
ENV PATH=/root/.local/bin:$PATH
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENTRYPOINT ["sh", "/app/entrypoint.sh"]
